import { useState, useEffect } from "react";
import { calculateLess, calculateAdd } from "../utils/calculator";
import { generateCode } from "../utils/codeGenerator";

export default function Search({ ratesData }) {
  const [search, setSearch] = useState("");
  const [results, setResults] = useState([]);

  useEffect(() => {
    if (!search.trim()) {
      setResults([]);
      return;
    }

    const value = search.trim().toUpperCase();

    const filtered = ratesData.filter((item) => {
      const rate = Number(item.ScreenSaleRate || 0);

      const name = String(item.ScreenName || "").toUpperCase();

      const less = calculateLess(rate, 12).finalRate.toString();

      const add = calculateAdd(rate, 12).finalRate.toString();

      const code = generateCode(rate).toUpperCase();

      return (
        name.includes(value) ||
        rate.toString().includes(value) ||
        less.includes(value) ||
        add.includes(value) ||
        code.includes(value)
      );
    });

    setResults(filtered);
  }, [search, ratesData]);

  return (
    <div className="card">
      <h2>🔍 Universal Search</h2>

      <input
        type="text"
        placeholder="Search Screen Name / Rate / Code"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />

      <p style={{ marginTop: "10px" }}>
        <b>Total Result :</b> {results.length}
      </p>

      {results.map((item, index) => {
        const rate = Number(item.ScreenSaleRate);

        const less = calculateLess(rate, 12).finalRate;

        const add = calculateAdd(rate, 12).finalRate;

        const code = generateCode(rate);

        const whatsappMessage = `━━━━━━━━━━━━━━━

🏢 SMMART EVENT RATE SYSTEM

📌 Screen Name : ${item.ScreenName}

💰 Original Rate : ₹${rate.toFixed(2)}

🏷️ Code : ${code}

📉 12% Less : ₹${less}

📈 12% Add : ₹${add}

━━━━━━━━━━━━━━━
Generated by
SMMART Event Rate System Pro`;

        return (
          <div
            key={index}
            className="result"
            style={{
              marginTop: "15px",
              border: "1px solid #ddd",
              borderRadius: "10px",
              padding: "15px",
            }}
          >
            <h3>{item.ScreenName}</h3>

            <p>
              <b>Original Rate :</b> ₹ {rate.toFixed(2)}
            </p>

            <p>
              <b>Original Code :</b> {code}
            </p>

            <p>
              <b>12% Less :</b> ₹ {less}
            </p>

            <p>
              <b>12% Add :</b> ₹ {add}
            </p>

            <button
              style={{
                marginTop: "10px",
                padding: "10px 18px",
                border: "none",
                borderRadius: "8px",
                background: "#25D366",
                color: "white",
                fontWeight: "bold",
                cursor: "pointer",
              }}
              onClick={() =>
                window.open(
                  `https://wa.me/?text=${encodeURIComponent(
                    whatsappMessage
                  )}`,
                  "_blank"
                )
              }
            >
              📱 Share on WhatsApp
            </button>
          </div>
        );
      })}

      {search !== "" && results.length === 0 && (
        <div className="result">
          <h3>❌ No Record Found</h3>
        </div>
      )}
    </div>
  );
}